name: wifi_chat
description: SOS Emergency Chat App

publish_to: "none" # not publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  flutter_local_notifications: ^17.2.2
  shared_preferences: ^2.2.2
  path: ^1.9.0
  flutter_foreground_task: ^9.1.0
  flutter_bluetooth_serial: ^0.4.0

  # Database
  sqflite: ^2.3.0

  # Date formatting
  intl: ^0.19.0

  # UUID for message IDs
  uuid: ^4.3.3

  nearby_connections:
    path: ./nearby_connections # Nearby Connections API (patched fork to fix AndroidManifest issue)

  # Location (if you need approximate location for discovery metadata)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/wifilogo.png
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/wifilogo.png
